apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-image-updater
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-image-updater
    spec:
      serviceAccountName: argocd-image-updater
      containers:
      - name: argocd-image-updater
        image: argoprojlabs/argocd-image-updater:latest
        args:
          - run
          - --argocd-server-addr=argocd-server.argocd.svc.cluster.local:443
          - --argocd-namespace=argocd
          - --loglevel=debug
          - --argocd-insecure
        env:
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-image-updater-secret
              key: argocd.token
        - name: ARGOCD_IMAGE_UPDATER_REGISTRIES
          value: /app/config/registries.conf
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: updater-config
          mountPath: /app/config
          readOnly: true
      volumes:
        - name: updater-config
          configMap:
            name: argocd-image-updater-config
