version: "3"

services:
  sonar_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./database:/var/lib/postgresql
    networks:
      - jenkins
  sonarqube:
    image: sonarqube:lts-community
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - ./app:/opt/sonarqube
    networks:
      - jenkins
    depends_on:
      - sonar_db 

networks:
  jenkins:
    external: true
