apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portfolio
  namespace: argocd
spec:
  destinations:
    - namespace: portfolio
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'