---
- name: Prepare a temporary SSH key from Vault
  hosts: localhost
  gather_facts: false

  vars_files:
    - group_vars/vault/vault.yml

  tasks:
    - name: Create temporary file
      tempfile:
        state: file
        suffix: _id_ed25519
      register: tmp_key

    - name: Save private key from Vault
      copy:
        content: "{{ vault_ssh_key_raw.data.data.private_key }}"
        dest: "{{ tmp_key.path }}"
        mode: "0600"

    - name: Assign the path with the key to all CICD hosts
      add_host:
        name: "{{ item }}"
        ansible_ssh_private_key_file: "{{ tmp_key.path }}"
      loop: "{{ groups['cicd'] }}"

    - name: Keep the key path as a fact
      set_fact:
        cicd_tmp_key_path: "{{ tmp_key.path }}"

- name: Docker installation
  hosts: all
  become: true
  roles:
    - docker

- name: Edit file /etc/resolv.conf
  hosts: cicd
  become: true
  roles:
   - resolv

- name: Jenkins and Sonarqube installation
  hosts: ci
  become: true
  roles:
   - jenkins
   - sonar

- name: K3S installation
  hosts: cd
  become: true
  roles:
   - k3s

- name: Delete temporary private key
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Delete temporary private key
      file:
        path: "{{ cicd_tmp_key_path }}"
        state: absent
      when: cicd_tmp_key_path is defined
