apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gh-private-key
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gh-private-key
    creationPolicy: Owner
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: github_key
        property: key
